### ISSUE TITLE
Don't magically change behavior when top-level overwrite is false

### ISSUE THREAD

**Issue by phenaproxima** [grasmash/composer-scaffold#25]
Right now, the README says this:

> Note that append operations override the overwrite option, and force a fresh copy every time.

This seems like WTFey magic to me, and potentially unexpected behavior. If append mode is fundamentally incompatible with `overwrite: false`, then it is misconfigured and should throw an exception. I propose we remove these sorts of things and, where possible, error our rather than default to potentially strange behavior.

**Comment by greg-1-anderson** [comment]
We should consider the use cases before changing the behavior from an override to an error.

Example 1:
> An ISP, e.g. Pantheon, ships a scaffolded settings.pantheon.php. A scaffolded settings.php file is also provided, but the later file has `"overwrite": false` set, so it will only scaffold the first time.  Thereafter, the user may commit the file and make their own modifications.

If a user now wants to append/prepend to settings.php, the current behavior allows this, whereas throwing an exception will not.

Example 2:
> A core developer has an existing site that appends to robots.txt in its top-level file-mappings. Said developer finds a bug in Drupal while working on this site, and wants to make a fix directly in the work site. The fix includes a change to one or more other scaffold files. They therefore set their top-level "symlink" option to `true` and run `composer install` again to convert all of their scaffold files to symlinks while making the fix.

In the current implementation, the robots.txt file will remain a copy with appended contents, whereas all of the other scaffold files will be symlinked to their respective source files.

The specifics of these examples may change from case-to-case; there are probably other instances where the append operation will be useful. It seems that these use cases are not absolute requirements; we could prevent them, and most of the common use cases would still be unaffected. However, going this route would occasionally be frustrating. If the sample site being used in debugging in example 2 were using a profile that appended to a core scaffold file, then the developer would have to modify the profile in order to use symlink mode.

I'm open to weighing the options for these two use cases and going either way, depending on whether we feel like the WTF or the potential for frustration is greater.

Neither of these examples rely on setting the top-level overwrite to false. I'm not sure that I can think of a use case for this option. I guess this is for users who want to commit all of their scaffold files and make a lot of customizations. Without top-level overwrite set to false, then every `composer install` et. al. would revert their customizations, requiring a review and `get checkout -- scaffolded-file.php`. I don't think that this use-case should behave differently than the others, but I'd be okay with removing the top-level overwrite option if we feel that the WTF factor is significantly greater here than in the other example use cases.

**Comment by grasmash** [comment]
Is the complaint here that, rather than setting the file to `false` the user should be required to specify the long form of `{ mode: "skip" }` ? 

If so, I don't feel strongly, but I like the short form.

**Comment by grasmash** [comment]
We could perhaps remove the overwrite, symlink, and prepend options and make them modes instead, thereby making options like overwrite and append mutually exclusive. E.g., the modes would then be:
```
append
place
prepend
replace
skip
symlink
```

We'd then need to use `path` the specify the path of the file to append or prepend.

**Comment by ryanaslett** [comment]
Maybe Im not following whats going on here, but AFAIC, a top level ` overwrite: false` means  *nothing else happens ever, Im now entirely and completely responsible for my file and I should not expect upstream changes* 

I dont understand the example 2 above.  Symlink: true should only ever be used when developing on core against a development site. It's sole purpose is to make it so that people can simultaneously create valid patches while having a functional site. It ought to never be used on an 'existing site' serving any actual traffic, because patches are against HEAD, and who's running head?

**Comment by greg-1-anderson** [comment]
> We could perhaps remove the overwrite, symlink, and prepend options and make them modes instead

The current implementation is already based on mutually-exclusive modes. If the mode is omitted, then in some cases it may be inferred from examining the options. Some options that are only usable in a certain mode may imply that said mode should be used when that option is present. There's a priority to the inferences, though, and it is not meaningful to attempt to combine two different modes.

> a top level overwrite: false means nothing else happens ever

That is true. The section of the README quoted, though, was talking about overriding a single-file `overwrite` option.

Perhaps it would be less confusing if the top-level option were renamed to `disable` or something like that. Maybe not `disable` (to avoid the double-negative of `"disable": false`), but some word other than `overwrite`.

**Comment by greg-1-anderson** [comment]
At the [composer in core initiative meeting](https://drupal.slack.com/archives/C392CHBEW/p1557940017075200), we decided to remove the top-level overwrite option and enhance the documentation to describe the recommended way to manage customizations to scaffold files.
