### ISSUE TITLE
Determine responsiblity for vendor cleanup.

### ISSUE THREAD

**Issue by ryanaslett** [grasmash/composer-scaffold#28]
So one of the things the orignal patch attempted to do was to roll in functionality from core's Drupal\Core\Composer\Composer.php

The use case is as follows:

> As a user who only has access to a single webroot on their host I need a version of drupal that is secure and does not have potentially insecure files in /vendor

 which means removal of certain testing directories from vendor dependencies.

Drupal core does this now when you run composer install by looking at a manifest of subdirs and folders an rm -rf'ing them.

So its essentially 'filesystem manipulation in prep for a site'.  What Im wondering is if we should also have this functionality in this scaffold plugin? https://github.com/drupal/drupal-scaffold/blob/8.6.x/src/Handler.php#L550 is roughly where the patch ended up.

**Comment by greg-1-anderson** [comment]
It looks like the original implementation hardcoded the list of things to clean up. This has the downside of requiring code changes if the list of things to clean up changes. Worse, this creates an additional dependency between the version of the software being cleaned up, and what version of the tool can be used to successfully sanitize the project.

I think it would be better to pull the list of vendor locations to sanitize from the composer.json of any component with assets to scaffold. In any event, this is an easy feature to add.

**Comment by greg-1-anderson** [comment]
In Drupal today, this feature is marked as deprecated:

> @deprecated in Drupal 8.7.0, will be removed before Drupal 9.0.0.

In the most recent [conversion of this project to a patch](https://www.drupal.org/files/issues/2019-04-13/2982684_89.patch), this feature was simply removed.

If we aspire to be included in Drupal 8.8.0, though, then we need to maintain this functionality, correct?

**Comment by greg-1-anderson** [comment]
Also, what is the strategy in Drupal 9.0.0? Is it assumed that `vendor` will always be outside of the document root in Drupal 9?

**Comment by greg-1-anderson** [comment]
@ryanaslett: The existing implementation you linked to sanitizes projects one at a time in the post-package event. I was wondering if we could do it at the tail end of the scaffold operation instead.

The advantage of post-package is that it's really secure. You get called every time Composer touches a package, so you know that you're sanitizing everything (and Composer isn't coming along after you and putting things back).

The disadvantage of doing it in post-package is that you won't necessarily have all packages installed at the time that the post package event is called. It would be better if we could list the projects that need to be sanitized in drupal/assets rather than hard-coding the list in the plugin (as I mention above). This is hard if drupal/assets hasn't been loaded onto the disk yet, and some other package needs to be sanitized in the post-package implementation.

The scaffold operation should already be running in most of the instances where it is needed (esp. after `composer install`, `composer create-project` and `composer update`). We might need to do some extra testing to make sure that `composer require` works right. Worse case, if a user runs the scaffold command directly, then they will know that all of their projects have been suitably sanitized.

Do you think that's good enough, or do we need the guarantee provided by the post-package event?

**Comment by paul-m** [comment]
The patch we had in the issue satisfied this need: https://www.drupal.org/project/drupal/issues/2982684#comment-13059286 In fact, @mixologic wrote it.. :-)

post-package doesn't really lose anything. It just means looking up the package in the hash for every package added, which isn't such a hardship.

+1 on making it configurable in `extra`. We're basically making this so that `drupal/legacy-project` can build, so the extra will be in that template.

I think we can't assume that Drupal 9 will always have a separate docroot. i'd rather be able to upgrade a site in-place than have to reconfigure my hosting for it. In practical terms, I assume basically zero new sites would use this.

There's also this: https://packagist.org/packages/barryvdh/composer-cleanup-plugin It's not configurable, but it also might automatically work for packages we add in the future.

**Comment by greg-1-anderson** [comment]
Do we want to require the root-level project to have the list of projects to sanitize? Doing that would potentially create a maintenance issue -- if Drupal's dependencies changes, causing a change in the required cleanup directories, then existing sites would not fully sanitize unless they updated their list.

I was considering that perhaps the list of sanitizations should go in some project like `drupal/assets`, which `drupal/core` would require. This way, if `drupal/core` added some more dependencies, then the list of sanitizations could be updated at the same time. Maybe put the assets in drupal/assets and the sanitizations directly in drupal/core to avoid version-alignment issues.

**Comment by greg-1-anderson** [comment]
I made a preliminary pull request to compare and contrast against the implementation in the patch.

If we decide to go with hardcoded cleanup rules, then I think we could just go with https://packagist.org/packages/barryvdh/composer-cleanup-plugin.

**Comment by paul-m** [comment]
Maybe the vendor cleanup behavior should be in core, since then we can at least potentially keep the test dirs and dependencies in line with the versions we're likely to see installed in the legacy project template.

I'm pretty sure @ryanaslett had some issues with the way it's implemented in core now, so we can address those, maybe even providing a subtree split for a vendor cleanup plugin.

**Comment by greg-1-anderson** [comment]
At the [composer in core initiative meeting](https://drupal.slack.com/archives/C392CHBEW/p1557940017075200), we decided that this should be done in a separate composer plugin, and there should be a metapackage that includes the needed composer installers.
