### ISSUE TITLE
Consider supporting PHP 5.x

### ISSUE THREAD

**Issue by greg-1-anderson** [grasmash/composer-scaffold#36]
In the [autoupdates slack channel:](https://drupal.slack.com/archives/C7QJNEY3E/p1557231825080000)

> There's no published core policy yet, but internally we only want to update dependencies to PHP 7 versions. Introducing PHP 7 syntax in core will make backports a nightmare.

We might need to remove our PHP 7-specific syntax in order to be added to Drupal core. This might be motivation to make this project a dependency of Drupal 8.8 rather than make it a part of it.

**Comment by ryanaslett** [comment]
The autoupdates initiative is also attempting to solve things for drupal 7, as such I don't believe that we're operating under the same constraints, and that there wont be any backports because it doesn't exist prior to 8.8.x

**Comment by greg-1-anderson** [comment]
> FYI that I haven't turned off PHP 5 testing on 8.8.x while we're still sorting out upgrade path criticals and whatnot

If we want to be able to integrate into the 8.x branch early, it might be a good to work with PHP 5. I am reluctant to remove the typehints, but I do think that we should strive to get the scaffold plugin integrated ASAP, so that we have as much time as possible to allow the features that depend on it (composer-ready downloads, etc.) to be completed in time for 8.8.

**Comment by xjm** [comment]
If it's a ton of work to remove, I wouldn't do so just yet, but if it's a simple change to remove the typehints, I'd recommend it. We don't have a discussion in the coding standards queue yet (to my knowledge) about the typehints yet either. I've always assumed we will adopt them as a standard, but as @greg-1-anderson mentioned, the simplest thing would be to adopt coding standards for the new PHP 7 syntaxes with D9.

**Comment by greg-1-anderson** [comment]
It's really easy to take them out -- it's a bit harder to put them back in again later.

**Comment by greg-1-anderson** [comment]
Here's a tool we might try:

https://murze.be/converting-php-7-code-to-equivalent-php-5-code

We could perhaps keep typehints in the source project, and filter the source through the tool to produce the core patch.  I'm not sure this is a great idea, though, as we have a different namespace than core does, and there are other transformations required go from the current form of the scaffold tool to the core patch.  Auto-converting to PHP 5 might be a good option if we decided to keep this as an external dependency instead of merging it into core.

**Comment by ryanaslett** [comment]
Do we have a distinction between 'entirely new code' and 'modifying existing code' for things like this? It seems to me that typehints are great, but I also understand not wanting to have the core queue flooded with a bunch of patches to update existing code with new php7 stuff.

**Comment by xjm** [comment]
So there are three ways coding standards/policy are enforced in core:

1. Automated testing
2. Coding standards rules and phpcs
3. Committer review

The only way the "entirely new code" vs. "modifying existing code" can be enforced is by _not_ using `#1` and `#2` and _only_ doing `#3`, which adds burden on committers, increases the chance of error, results in more overhead when people forget and do PHP 7 things in stuff that will be backported, etc. Also from a policy perspective this should be discussed on d.o, not GitHub; I just weighed in here because an incorrect recommendation was made in Slack for another initiative. :) 

Since this initial development isn't happening on d.o I think @greg-1-anderson 's preference to leave them for now is OK and not likely to be disruptive. Edit: Or in other words, cross that bridge once this does hit the core queue, and just be aware of it.

**Comment by greg-1-anderson** [comment]
At the [composer in core initiative meeting](https://drupal.slack.com/archives/C392CHBEW/p1557940017075200), we decided that we should remove the typehints in this project as a first step.
